welcome: "Привет, с помощью этого бота вы можете заполнить форму для анонса мероприятия в канал чата Бициклы, пиво и мачки: https://t.me/veloserbia. Если анонс будет одобрен администраторами, то он будет автоматически опубликован в канале."
templates:
  - title: "Анонс покатушки"
    description: "Эта форма для анонсов стандартных однодневных покатушек (не бреветы, не походы, без заброса на транспорте)."
    complete: "Спасибо, что заполнили форму, если она будет утверждена администраторами, то будет автоматически опубликована в канале."
    entries:
    - mode: "text"
      title: "Город старта"
      incorrect: "Введите по-нормальному, пожалуйста."
      description: "Откуда стартует покатушка? В любом понятном виде, например: Белград, БГ, НС, Нови Сад и т.д."
    - mode: "text"
      title: "Краткое название покатушки"
      incorrect: "Введите по-нормальному, пожалуйста."
      description: "Кратко и понятно на ваше усмотрение, без лишних деталей, например: Едем в Бачку Паланку по полям. Вы сможете добавить больше информации в следующих полях."
    - mode: "number"
      title: "Приблизительная длина маршрута"
      incorrect: "Введите по-нормальному, пожалуйста. Без указания единиц измерения, просто число."
      description: "Не обязательно точно, просто приблизительно, без указания единиц измерения, например: 50."
    - mode: "oneof"
      title: "Формат покатушки"
      incorrect: "Выберите один из вариантов."
      description: "Насколько хардкорная покатушка, предполагается ли ломить или чилить или вообще доехать до ближайшей пивнухи."
      options:
        - "🔵 Чилл и ультраматрас"
        - "🟢 Не спешим, но хочется ехать"
        - "🟡 Плотно и с легкой нагрузкой"
        - "🟠 Едем по пульсу без лишних остановок"
        - "🔴 FTP OVER 9000 (только для профи)"
    - mode: "text"
      title: "Дата и время старта"
      incorrect: "Введите по-нормальному, пожалуйста."
      description: "В любом формате, но так, чтобы было понятно. Например: пятница, 7 июня в 19:00."
    - mode: "text"
      title: "Локация точки старта"
      incorrect: "Введите по-нормальному, пожалуйста."
      description: "Желательно ссылкой на точку на Google Maps, например: https://maps.app.goo.gl/SuYpFQ6bfEPzD1747. Можете добавить описание, например: на въезде в Лиманский парк под флагами."
    - mode: "oneof"
      title: "Какой нужен велосипед"
      incorrect: "Выберите один из вариантов."
      description: "Подразумевается, что на шоссере не ездят по грунтовым дорогам, а на исключительно асфальтовом маршруте не нужен МТБ."
      options:
        - "Любой"
        - "Шоссе"
        - "Сингл / фикс"
        - "Гревел / циклокросс"
        - "МТБ"
        - "Фетбайк"
        - "Сити / круизер"
        - "E-bike"
    - mode: "text"
      title: "Описание маршрута"
      incorrect: "Введите по-нормальному, пожалуйста."
      description: "Любая дополнительная информация, которую вы считаете нужной. Если есть ссылка на маршут в Stava, Komoot или другом сервисе, то добавьте ее тут."
