welcome: "Привет, с помощью этого бота вы можете заполнить форму для анонса мероприятия в канал https://t.me/veloserbia_ride. Если анонс будет одобрен администраторами, то он будет автоматически опубликован в канале."
templates:
  - title: "Анонс покатушки"
    description: "Эта форма для анонсов стандартных однодневных покатушек (не бреветы, не походы, без заброса на транспорте)."
    toend: "Пожалуйста, используйте реакции, чтобы автор знал собирается ли кто-нибудь присоединиться к мероприятию. Спасибо!"
    complete: "Спасибо, что заполнили форму, если она будет утверждена администраторами, то будет автоматически опубликована в канале."
    entries:
    - mode: "text"
      title: "🌐 Город старта"
      incorrect: "Введите по-нормальному, пожалуйста."
      description: "Откуда стартует покатушка? В любом понятном виде, например: Белград, БГ, НС, Нови Сад и т.д."
    - mode: "text"
      title: "📝 Название мероприятия"
      incorrect: "Введите по-нормальному, пожалуйста."
      description: "Кратко и понятно на ваше усмотрение, без лишних деталей, например: Едем в Бачку Паланку по полям. Вы сможете добавить больше информации в следующих полях."
    - mode: "url"
      title: "🔗 Ссылка на маршрут"
      skippable: true
      description: "Укажите ссылку на маршрут (Strava, Komoot или любой другой ресурс).\nℹ️ Это не обязательное поле."
      incorrect: "Введите по-нормальному, пожалуйста. Просто скопируйте ссылка из браузера. Напоминаю, что это не обязательное поле.
    - mode: "number"
      title: "🛣️ Длина маршрута (км)"
      incorrect: "Введите по-нормальному, пожалуйста. Без указания единиц измерения, просто число."
      description: "Не обязательно точно, просто приблизительно, без указания единиц измерения, например: 50."
    - mode: "number"
      title: "🏔️ Набор высоты (м)"
      skippable: true
      incorrect: "Введите по-нормальному, пожалуйста. Без указания единиц измерения, просто число."
      description: "Не обязательно точно, просто приблизительно, без указания единиц измерения, например: 50. Если планируется заезд по плоскачу, нажмите кнопку пропуска.\nℹ️ Это не обязательное поле."
    - mode: "oneof"
      title: "💪 Формат мероприятия"
      incorrect: "Выберите один из вариантов."
      description: "Насколько хардкорная покатушка, предполагается ли ломить или чилить или вообще доехать до ближайшей пивнухи."
      options:
        - "🔵 Прогулочный"
        - "🟢 Неспешный"
        - "🟡 Фитнесовый"
        - "🟠 Спортивный"
        - "🔴 Профессиональный"
    - mode: "text"
      title: "🗓️ Дата и время старта"
      incorrect: "Введите по-нормальному, пожалуйста."
      description: "В любом формате, но так, чтобы было понятно. Например: пятница, 7 июня в 19:00."
    - mode: "text"
      title: "📍 Локация точки старта"
      incorrect: "Введите по-нормальному, пожалуйста."
      description: "Желательно ссылкой на точку на Google Maps, например: https://maps.app.goo.gl/SuYpFQ6bfEPzD1747. Можете добавить описание, например: на въезде в Лиманский парк под флагами."
    - mode: "oneof"
      title: "🚲 Требуемый велосипед"
      incorrect: "Выберите один из вариантов."
      description: "Подразумевается, что на шоссере не ездят по грунтовым дорогам, а на исключительно асфальтовом маршруте не нужен МТБ."
      options:
        - "Любой"
        - "Шоссейный"
        - "Гревел"
        - "Шоссейный / гревел"
        - "МТБ"
    - mode: "text"
      title: "📋 Описание мероприятия"
      skippable: true
      incorrect: "Введите по-нормальному, пожалуйста."
      description: "Любая дополнительная информация, которую вы считаете нужной.\nℹ️ Это не обязательное поле."
